
GET  http://localhost:3000

###

GET  http://localhost:3000/api/events

###

GET  http://localhost:3000/api/members
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNWFjMDQyMWUwZWEzNjM3ZmYxMzk5OWQ3IiwiaWF0IjoxNTIyNTYzMDI5fQ.lA0KgufrtSGs9jpaFlaJMtsjPEsOLABEL3xHWOybyoE

###
POST http://localhost:3000/api/register HTTP/1.1
Content-Type: application/json

{
	"email": "2@1.com",
	"password": "1"
}

###

POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
	"email": "kunalganglani@gmail.com",
	"password": "asdfjkl12"
}

###


GET  http://localhost:3000/api/users

###

GET  http://localhost:3000/api/users/5ac285a415cecf1ac71a892e

###

DELETE http://localhost:3000/api/users/5ac285a415cecf1ac71a892e
